INFO:root:API created
INFO:root:Searching for tweets
INFO:root:Found Gnameless üá®üá¶:RT @WyzeCam: App versions 2.14.33 for Android and 2.14.22 for iOS are releasing today along with Wyze Band firmware 1.0.8.30! This adds a r‚Ä¶
INFO:root:Found SPS:@SonisSecurity @OrisecLtd It annoyed me that the CP-25 became obsolete about 3 months after I started using them. T‚Ä¶ https://t.co/mRDGH61rVV
INFO:root:Found Scott Waldron:https://t.co/Gx1TC69VoD . 

The Canon EOS M50 Mark II looks like a firmware update, though it's possible they tweak‚Ä¶ https://t.co/g06oALRzvG
INFO:root:Found Bill Stater:@CanonUSA could you please release a firmware update for the M6 mkii to address overheating in video mode? It's a f‚Ä¶ https://t.co/CNGZ9kJtoG
INFO:root:Found PNSQC:If we release a critical infrastructure product with a bug, especially a bad one, it can be extremely costly to cus‚Ä¶ https://t.co/rdist8ZZMV
INFO:root:Found LMI Technologies:Join us for a webinar that covers the exciting new updates and functionalities in the upcoming #Gocator 6.1 Beta fi‚Ä¶ https://t.co/0wKROTc77m
INFO:root:Found VinylsExpert:RT @WyzeCam: App versions 2.14.33 for Android and 2.14.22 for iOS are releasing today along with Wyze Band firmware 1.0.8.30! This adds a r‚Ä¶
INFO:root:Found Wyze:App versions 2.14.33 for Android and 2.14.22 for iOS are releasing today along with Wyze Band firmware 1.0.8.30! Th‚Ä¶ https://t.co/BwdtcLeS5w
INFO:root:Found Does it matter?:@DxrkenedSoulz Thats fine and understandable.  Please keep in mind this is not final firmware or game release code. Good or bad.
INFO:root:Found Jane Cassell:RT @cstalhood: #Citrix Gateway now supports nFactor authentication with Standard license. https://t.co/rhmb6cAic2
INFO:root:Found AutomationDistrib:Register now for LMI's webinar for Gocator 6.1 beta firmware release in late November, plus a preview of the v7.0 B‚Ä¶ https://t.co/UdUi3aR6cC
INFO:root:Found Open Source Electric Vehicles:RT @OpenVehicles: @glynhudson @dpeilow @RouteBetter The upcoming 3.3 release of OVMS firmware will allow much cleaner and simpler installat‚Ä¶
INFO:root:Found Kirby0Louise:@Optimus_Code I just want Sony to release the firmware update for the X900H to support VRR/ALLM/Dolby Vision/etc...‚Ä¶ https://t.co/kFUnF89kkQ
INFO:root:Found 50_Year-old-virgin:RT @WyzeCam: We're releasing Wyze Cam and Wyze Cam Pan firmware 4.X.6.193! This resolves the time zone bug found in last week's firmware th‚Ä¶
INFO:root:Found 50_Year-old-virgin:RT @WyzeCam: Wyze Cam v2 and Pan firmware are released! 4.X.6.191 fixes bugs that could cause reboots, Cam Plus devices to not record motio‚Ä¶
INFO:root:Found ssieg:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos - The Verge https://t.co/mjqlWL8Odp #Birdwatching
INFO:root:Found Vinhsanity:This is what the original release of the Nikon Z line should have been! Z 6ii is much cheaper than the Canon R6 tha‚Ä¶ https://t.co/V2f7ZRLwxZ
INFO:root:Found Brittany Harrison:So excited! Invested in a Canon PowerShot G7X Mark II ! Going to have a brand new avatar for all things RandomAwkwa‚Ä¶ https://t.co/BQvcp7YR8J
INFO:root:Found ·µó·µí·µà·µàÀ°·µâ ≥·µé ùêáùêàùêåùêÄùêñùêÄùêëùêà:@reiketsuhinata üçì: Yesterday.

It's not canon or anything. I just use the release date for the episode with her bir‚Ä¶ https://t.co/ae9HWYY8TP
INFO:root:Found Joshua Verwers:So @Canon announced the nÃ∂eÃ∂wÃ∂ M50. Loved reading all those nÃ∂eÃ∂wÃ∂ specs.

Wait a minute... ü§î Did they just copy th‚Ä¶ https://t.co/qMUUkQoRLO
INFO:root:Found Mojibola:RT @Sisi_Eko15: Translation: SARS killed her older bro and they refused to release his body till she got help from a radio presenter. Her m‚Ä¶
INFO:root:Found Farzal Khan:RT @FarzalSays: Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/UyVXrCKq0m Canon has announced the PowerSh‚Ä¶
INFO:root:Found geraldine bachanes RN:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/lwvT0eSy24
INFO:root:Found Mojibola:RT @Adebayo_Ralph: THIS IS THE REPORT FROM THE HOSPITAL. 

NATIONAL HOSPITAL WANTS TO RELEASE THE THUGS AFTER ADMINISTERING FIRST AID. WE N‚Ä¶
INFO:root:Found Vencislav Kostadinov:The Peeping Tom‚Äôs camera is here üòÇüòÇüòÇ https://t.co/3ApC4veb8w
INFO:root:Found Noon3:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/ol1Dt7Yxjk via @Verge
INFO:root:Found Alejandro Sewrjugin:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/porApOrbY2 https://t.co/SPCeot4TTj
INFO:root:Found Farzal Khan:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/UyVXrCKq0m Canon has announced the‚Ä¶ https://t.co/qMYTGeV4wG
INFO:root:Found Socially:The Verge - All Content Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/tEmqOJ940n
INFO:root:Found DIE WIENBURG.:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/xZYTG82Hkt #technologie #feedly
INFO:root:Found S√©bastien \(¬∞-¬∞)/:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found Camera Times:Fujifilm X-S10 &amp; 10-24mm f/4 R OIS WR Lens Full Specs, Press Release &amp; Pricing Info https://t.co/xHszO8afKB
INFO:root:Found Jaran Images & Phuket Wedding Photography:RT @JosephCristina: Fujifilm X-S10 Press Release and Specs Leaked The Fujifilm X-S10 press release and full specs have now been leaked by n‚Ä¶
INFO:root:Found Joseph Cristina:Fujifilm X-S10 Press Release and Specs Leaked The Fujifilm X-S10 press release and full specs have now been leaked‚Ä¶ https://t.co/M0H8PtLZdw
INFO:root:Found „ÅÇ„Åü„Åü„ÇÅ„Å¶„Åá„Çì!:„Åä„ÄÄFujifilm X-S10 Press Release and Specs Leaked https://t.co/HiJiPGdYVO
INFO:root:Found taywa:RT @photorumors: More info added on the Fujifilm Fujinon XF 10-24mm f/4 R OIS WR lens:

https://t.co/kCwPnnLc8A https://t.co/ygQL5yKeWj
INFO:root:Found taywa:RT @Fuji_Addict: Full Fujifilm X-S10 Press Release and Spec Leak https://t.co/brCDGRvcRb

#Fujifilm #Fujifilmx_us #Fujifilm_xseries #Fujifi‚Ä¶
INFO:root:Found taywa:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found KameraCrafts:RT @photorumors: More info added on the Fujifilm Fujinon XF 10-24mm f/4 R OIS WR lens:

https://t.co/kCwPnnLc8A https://t.co/ygQL5yKeWj
INFO:root:Found KameraCrafts:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found Megateman:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found grdkingdom:RT @Todofujidotcom: Fujifilm X-S10 Press Release and Specs Leaked https://t.co/JZqz18Nqum @fujirumors https://t.co/ejasHsEx7b
INFO:root:Found David Fleetwood:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found Todofuji:Fujifilm X-S10 Press Release and Specs Leaked https://t.co/JZqz18Nqum @fujirumors https://t.co/ejasHsEx7b
INFO:root:Found Œ£œãŒªŒµR..üíÆ ‚ô™‚ô™‚ô™:Fujifilm X-S10 Press Release and Specs Leaked https://t.co/upsEXhHDCO
INFO:root:Found Vinhsanity:This is what the original release of the Nikon Z line should have been! Z 6ii is much cheaper than the Canon R6 tha‚Ä¶ https://t.co/V2f7ZRLwxZ
INFO:root:Found The Pixel Connection:Nikon has just released the Z 6II and Z 7II! They are available on our website now for preorders! These cameras inc‚Ä¶ https://t.co/2JWzMyCnI2
INFO:root:Found Nikon India Official:RT @4psNews: Nikon India Private Ltd. 100% subsidiary of Nikon Corporation Tokyo, is pleased to announce the release of the WR-R11a and WR-‚Ä¶
INFO:root:Found 4ps News:Nikon India Private Ltd. 100% subsidiary of Nikon Corporation Tokyo, is pleased to announce the release of the WR-R‚Ä¶ https://t.co/IKskVaysVO
INFO:root:Found Nikon India Official:RT @4psNews: Nikon India Private Ltd. is pleased to announce the release of its new  high-resolution, FX-format (full-frame) mirrorless cam‚Ä¶
INFO:root:Found yik keng chan bird:Nikon Z6 II and Z7 II release date, price and all the details on its new mirrorless cameras https://t.co/1QAUVa68FY
INFO:root:Found LeZot Camera:RT @ClickErik: Leica fans: The Leica is the most perfect camera there is.
Also Leica fans: Check out my M3 with a grip and a winder and a r‚Ä¶
INFO:root:Found 4ps News:Nikon India Private Ltd. is pleased to announce the release of its new  high-resolution, FX-format (full-frame) mir‚Ä¶ https://t.co/IWhRxHLnIB
INFO:root:Found Stand Up To Racism North Norfolk:The brilliant and powerful 1979 'Original Selfies' project.
Inviting passers-by into their street pop-up studio, ph‚Ä¶ https://t.co/jTbOLUoOj7
INFO:root:Found „Åü„Å¨„Åç:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found Web & Cloud LLC:Nikon Z6 II and Z7 II release date, price and all the details on its new mirrorless cameras https://t.co/ompnoWlZdR
INFO:root:Found „ÇÇ„Å®„Åô„Åì„Åô„Åì:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found ÏôÄ! Ïù¥Ï†ú ÎÇòÎäî Í±¥Í∞ïÏì∞Î†àÍ∏∞ ÌååÏ¶àÎãòÏù¥ÏãúÎã§.:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found „Åπ„ÇÅ„Çìüì∑:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found 456:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found ‡∏ø‚±§√ò‚Çµ‚Ç≠ üéÉ:RT @SonyPictures: Sony Pictures to release Spider-Man 4 on May 6, 2011.
INFO:root:Found Begaria:@GoldBeard13 That's my point:  Sony has announced two of its launch titles (Miles and Sackboy) as coming to PS4 at‚Ä¶ https://t.co/tXwumqwnE6
INFO:root:Found Kaushik choudhury:RT @indiangamer537: @geronimo_73 Wow, never thought I'd see the day where Sony India takes a backseat and doesn't even bother to reveal pri‚Ä¶
INFO:root:Found Begaria:There are rumors circling around that Demon's Souls is also coming to PS4

I say this:  Sony announced Miles Morale‚Ä¶ https://t.co/qP44BW2nFf
INFO:root:Found üå∑üå∏üåπüå∫üåªüåº ‚óã Primus Interpares:RT @TheFilmExiles: The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular video g‚Ä¶
INFO:root:Found The Digital Fortress:RT @manfightdragon: The idea that the release of my patch hinges on Sony failing to deliver something is clearly not in line with reality.‚Ä¶
INFO:root:Found Millennial Mike #Boosh:RT @TheFilmExiles: The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular video g‚Ä¶
INFO:root:Found Brandon Valenza:RT @TheFilmExiles: The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular video g‚Ä¶
INFO:root:Found The Film Exiles Podcast:The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular vi‚Ä¶ https://t.co/hDUT0XOsgq
INFO:root:Found Young Joe:@thicc_bunni @JasonSh40173483 @PlayStation I was talking about pre orders, not the release, many people wanna get o‚Ä¶ https://t.co/O4QDMDwJ8x
INFO:root:Found Vinhsanity:This is what the original release of the Nikon Z line should have been! Z 6ii is much cheaper than the Canon R6 tha‚Ä¶ https://t.co/V2f7ZRLwxZ
INFO:root:Found bandicoot:@geronimo_73 Wow, never thought I'd see the day where Sony India takes a backseat and doesn't even bother to reveal‚Ä¶ https://t.co/Sco1Xtarnk
INFO:root:Found Under Ach1ever:@evshrug I'm just waiting to see what's what from other sources than Sony. I find it somewhat odd that they have he‚Ä¶ https://t.co/gExxYA3HdG
INFO:root:Found KOMA:@Xd12Im @cakirgenc_alper @BeatSaber Yes, that is how math works. They have the update ready, the problem is getting‚Ä¶ https://t.co/8qJYktj9ac
INFO:root:Found LGTWO‚Ñ† Support:RT @GeovanyNota: @SonnyDigital Maybe record something like this Sony?NEW RELEASE @amberthegemini GridLock by Amber TheGemini THANK YOU IN A‚Ä¶
INFO:root:Waiting...
INFO:root:Searching for tweets
INFO:root:Found Gnameless üá®üá¶:RT @WyzeCam: App versions 2.14.33 for Android and 2.14.22 for iOS are releasing today along with Wyze Band firmware 1.0.8.30! This adds a r‚Ä¶
INFO:root:Found SPS:@SonisSecurity @OrisecLtd It annoyed me that the CP-25 became obsolete about 3 months after I started using them. T‚Ä¶ https://t.co/mRDGH61rVV
INFO:root:Found Scott Waldron:https://t.co/Gx1TC69VoD . 

The Canon EOS M50 Mark II looks like a firmware update, though it's possible they tweak‚Ä¶ https://t.co/g06oALRzvG
INFO:root:Found Bill Stater:@CanonUSA could you please release a firmware update for the M6 mkii to address overheating in video mode? It's a f‚Ä¶ https://t.co/CNGZ9kJtoG
INFO:root:Found PNSQC:If we release a critical infrastructure product with a bug, especially a bad one, it can be extremely costly to cus‚Ä¶ https://t.co/rdist8ZZMV
INFO:root:Found LMI Technologies:Join us for a webinar that covers the exciting new updates and functionalities in the upcoming #Gocator 6.1 Beta fi‚Ä¶ https://t.co/0wKROTc77m
INFO:root:Found VinylsExpert:RT @WyzeCam: App versions 2.14.33 for Android and 2.14.22 for iOS are releasing today along with Wyze Band firmware 1.0.8.30! This adds a r‚Ä¶
INFO:root:Found Wyze:App versions 2.14.33 for Android and 2.14.22 for iOS are releasing today along with Wyze Band firmware 1.0.8.30! Th‚Ä¶ https://t.co/BwdtcLeS5w
INFO:root:Found Does it matter?:@DxrkenedSoulz Thats fine and understandable.  Please keep in mind this is not final firmware or game release code. Good or bad.
INFO:root:Found Jane Cassell:RT @cstalhood: #Citrix Gateway now supports nFactor authentication with Standard license. https://t.co/rhmb6cAic2
INFO:root:Found AutomationDistrib:Register now for LMI's webinar for Gocator 6.1 beta firmware release in late November, plus a preview of the v7.0 B‚Ä¶ https://t.co/UdUi3aR6cC
INFO:root:Found Open Source Electric Vehicles:RT @OpenVehicles: @glynhudson @dpeilow @RouteBetter The upcoming 3.3 release of OVMS firmware will allow much cleaner and simpler installat‚Ä¶
INFO:root:Found Kirby0Louise:@Optimus_Code I just want Sony to release the firmware update for the X900H to support VRR/ALLM/Dolby Vision/etc...‚Ä¶ https://t.co/kFUnF89kkQ
INFO:root:Found 50_Year-old-virgin:RT @WyzeCam: We're releasing Wyze Cam and Wyze Cam Pan firmware 4.X.6.193! This resolves the time zone bug found in last week's firmware th‚Ä¶
INFO:root:Found 50_Year-old-virgin:RT @WyzeCam: Wyze Cam v2 and Pan firmware are released! 4.X.6.191 fixes bugs that could cause reboots, Cam Plus devices to not record motio‚Ä¶
INFO:root:Found ssieg:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos - The Verge https://t.co/mjqlWL8Odp #Birdwatching
INFO:root:Found Vinhsanity:This is what the original release of the Nikon Z line should have been! Z 6ii is much cheaper than the Canon R6 tha‚Ä¶ https://t.co/V2f7ZRLwxZ
INFO:root:Found Brittany Harrison:So excited! Invested in a Canon PowerShot G7X Mark II ! Going to have a brand new avatar for all things RandomAwkwa‚Ä¶ https://t.co/BQvcp7YR8J
INFO:root:Found ·µó·µí·µà·µàÀ°·µâ ≥·µé ùêáùêàùêåùêÄùêñùêÄùêëùêà:@reiketsuhinata üçì: Yesterday.

It's not canon or anything. I just use the release date for the episode with her bir‚Ä¶ https://t.co/ae9HWYY8TP
INFO:root:Found Joshua Verwers:So @Canon announced the nÃ∂eÃ∂wÃ∂ M50. Loved reading all those nÃ∂eÃ∂wÃ∂ specs.

Wait a minute... ü§î Did they just copy th‚Ä¶ https://t.co/qMUUkQoRLO
INFO:root:Found Mojibola:RT @Sisi_Eko15: Translation: SARS killed her older bro and they refused to release his body till she got help from a radio presenter. Her m‚Ä¶
INFO:root:Found Farzal Khan:RT @FarzalSays: Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/UyVXrCKq0m Canon has announced the PowerSh‚Ä¶
INFO:root:Found geraldine bachanes RN:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/lwvT0eSy24
INFO:root:Found Mojibola:RT @Adebayo_Ralph: THIS IS THE REPORT FROM THE HOSPITAL. 

NATIONAL HOSPITAL WANTS TO RELEASE THE THUGS AFTER ADMINISTERING FIRST AID. WE N‚Ä¶
INFO:root:Found Vencislav Kostadinov:The Peeping Tom‚Äôs camera is here üòÇüòÇüòÇ https://t.co/3ApC4veb8w
INFO:root:Found Noon3:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/ol1Dt7Yxjk via @Verge
INFO:root:Found Alejandro Sewrjugin:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/porApOrbY2 https://t.co/SPCeot4TTj
INFO:root:Found Farzal Khan:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/UyVXrCKq0m Canon has announced the‚Ä¶ https://t.co/qMYTGeV4wG
INFO:root:Found Socially:The Verge - All Content Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/tEmqOJ940n
INFO:root:Found DIE WIENBURG.:Canon‚Äôs PowerShot Zoom is like a pocket telescope that takes photos https://t.co/xZYTG82Hkt #technologie #feedly
INFO:root:Found S√©bastien \(¬∞-¬∞)/:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found Camera Times:Fujifilm X-S10 &amp; 10-24mm f/4 R OIS WR Lens Full Specs, Press Release &amp; Pricing Info https://t.co/xHszO8afKB
INFO:root:Found Jaran Images & Phuket Wedding Photography:RT @JosephCristina: Fujifilm X-S10 Press Release and Specs Leaked The Fujifilm X-S10 press release and full specs have now been leaked by n‚Ä¶
INFO:root:Found Joseph Cristina:Fujifilm X-S10 Press Release and Specs Leaked The Fujifilm X-S10 press release and full specs have now been leaked‚Ä¶ https://t.co/M0H8PtLZdw
INFO:root:Found „ÅÇ„Åü„Åü„ÇÅ„Å¶„Åá„Çì!:„Åä„ÄÄFujifilm X-S10 Press Release and Specs Leaked https://t.co/HiJiPGdYVO
INFO:root:Found taywa:RT @photorumors: More info added on the Fujifilm Fujinon XF 10-24mm f/4 R OIS WR lens:

https://t.co/kCwPnnLc8A https://t.co/ygQL5yKeWj
INFO:root:Found taywa:RT @Fuji_Addict: Full Fujifilm X-S10 Press Release and Spec Leak https://t.co/brCDGRvcRb

#Fujifilm #Fujifilmx_us #Fujifilm_xseries #Fujifi‚Ä¶
INFO:root:Found taywa:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found KameraCrafts:RT @photorumors: More info added on the Fujifilm Fujinon XF 10-24mm f/4 R OIS WR lens:

https://t.co/kCwPnnLc8A https://t.co/ygQL5yKeWj
INFO:root:Found KameraCrafts:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found Megateman:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found grdkingdom:RT @Todofujidotcom: Fujifilm X-S10 Press Release and Specs Leaked https://t.co/JZqz18Nqum @fujirumors https://t.co/ejasHsEx7b
INFO:root:Found David Fleetwood:RT @Fujirumors: Fujifilm X-S10 Press Release and Specs Leaked
https://t.co/Gp0UkteEF3 https://t.co/zN8v8mTQzH
INFO:root:Found Todofuji:Fujifilm X-S10 Press Release and Specs Leaked https://t.co/JZqz18Nqum @fujirumors https://t.co/ejasHsEx7b
INFO:root:Found Œ£œãŒªŒµR..üíÆ ‚ô™‚ô™‚ô™:Fujifilm X-S10 Press Release and Specs Leaked https://t.co/upsEXhHDCO
INFO:root:Found Vinhsanity:This is what the original release of the Nikon Z line should have been! Z 6ii is much cheaper than the Canon R6 tha‚Ä¶ https://t.co/V2f7ZRLwxZ
INFO:root:Found The Pixel Connection:Nikon has just released the Z 6II and Z 7II! They are available on our website now for preorders! These cameras inc‚Ä¶ https://t.co/2JWzMyCnI2
INFO:root:Found Nikon India Official:RT @4psNews: Nikon India Private Ltd. 100% subsidiary of Nikon Corporation Tokyo, is pleased to announce the release of the WR-R11a and WR-‚Ä¶
INFO:root:Found 4ps News:Nikon India Private Ltd. 100% subsidiary of Nikon Corporation Tokyo, is pleased to announce the release of the WR-R‚Ä¶ https://t.co/IKskVaysVO
INFO:root:Found Nikon India Official:RT @4psNews: Nikon India Private Ltd. is pleased to announce the release of its new  high-resolution, FX-format (full-frame) mirrorless cam‚Ä¶
INFO:root:Found yik keng chan bird:Nikon Z6 II and Z7 II release date, price and all the details on its new mirrorless cameras https://t.co/1QAUVa68FY
INFO:root:Found LeZot Camera:RT @ClickErik: Leica fans: The Leica is the most perfect camera there is.
Also Leica fans: Check out my M3 with a grip and a winder and a r‚Ä¶
INFO:root:Found 4ps News:Nikon India Private Ltd. is pleased to announce the release of its new  high-resolution, FX-format (full-frame) mir‚Ä¶ https://t.co/IWhRxHLnIB
INFO:root:Found Stand Up To Racism North Norfolk:The brilliant and powerful 1979 'Original Selfies' project.
Inviting passers-by into their street pop-up studio, ph‚Ä¶ https://t.co/jTbOLUoOj7
INFO:root:Found „Åü„Å¨„Åç:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found Web & Cloud LLC:Nikon Z6 II and Z7 II release date, price and all the details on its new mirrorless cameras https://t.co/ompnoWlZdR
INFO:root:Found „ÇÇ„Å®„Åô„Åì„Åô„Åì:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found ÏôÄ! Ïù¥Ï†ú ÎÇòÎäî Í±¥Í∞ïÏì∞Î†àÍ∏∞ ÌååÏ¶àÎãòÏù¥ÏãúÎã§.:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found „Åπ„ÇÅ„Çìüì∑:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found 456:RT @nikonrumors: I think B&amp;H has the wrong price for the Nikon Z7 II - it‚Äôs $300 cheaper or the press release is wrong:

https://t.co/emUmy‚Ä¶
INFO:root:Found alex:RT @SonyPictures: Sony Pictures to release Spider-Man 4 on May 6, 2011.
INFO:root:Found ‡∏ø‚±§√ò‚Çµ‚Ç≠ üéÉ:RT @SonyPictures: Sony Pictures to release Spider-Man 4 on May 6, 2011.
INFO:root:Found Begaria:@GoldBeard13 That's my point:  Sony has announced two of its launch titles (Miles and Sackboy) as coming to PS4 at‚Ä¶ https://t.co/tXwumqwnE6
INFO:root:Found Kaushik choudhury:RT @indiangamer537: @geronimo_73 Wow, never thought I'd see the day where Sony India takes a backseat and doesn't even bother to reveal pri‚Ä¶
INFO:root:Found Begaria:There are rumors circling around that Demon's Souls is also coming to PS4

I say this:  Sony announced Miles Morale‚Ä¶ https://t.co/qP44BW2nFf
INFO:root:Found üå∑üå∏üåπüå∫üåªüåº ‚óã Primus Interpares:RT @TheFilmExiles: The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular video g‚Ä¶
INFO:root:Found The Digital Fortress:RT @manfightdragon: The idea that the release of my patch hinges on Sony failing to deliver something is clearly not in line with reality.‚Ä¶
INFO:root:Found Millennial Mike #Boosh:RT @TheFilmExiles: The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular video g‚Ä¶
INFO:root:Found Brandon Valenza:RT @TheFilmExiles: The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular video g‚Ä¶
INFO:root:Found The Film Exiles Podcast:The first official trailer for #MonsterHunter has arrived from Sony Pictures!

The movie is based on the popular vi‚Ä¶ https://t.co/hDUT0XOsgq
INFO:root:Found Young Joe:@thicc_bunni @JasonSh40173483 @PlayStation I was talking about pre orders, not the release, many people wanna get o‚Ä¶ https://t.co/O4QDMDwJ8x
INFO:root:Found Vinhsanity:This is what the original release of the Nikon Z line should have been! Z 6ii is much cheaper than the Canon R6 tha‚Ä¶ https://t.co/V2f7ZRLwxZ
INFO:root:Found bandicoot:@geronimo_73 Wow, never thought I'd see the day where Sony India takes a backseat and doesn't even bother to reveal‚Ä¶ https://t.co/Sco1Xtarnk
INFO:root:Found Under Ach1ever:@evshrug I'm just waiting to see what's what from other sources than Sony. I find it somewhat odd that they have he‚Ä¶ https://t.co/gExxYA3HdG
INFO:root:Found KOMA:@Xd12Im @cakirgenc_alper @BeatSaber Yes, that is how math works. They have the update ready, the problem is getting‚Ä¶ https://t.co/8qJYktj9ac
INFO:root:Waiting...
INFO:root:API created
INFO:root:Searching for tweets
INFO:root:Retweeted tweet from Gnameless üá®üá¶
INFO:root:API created
INFO:root:Searching for tweets
INFO:root:Retweeted tweet from ssieg
INFO:root:Retweeted tweet from Vinhsanity
INFO:root:Retweeted tweet from Brittany Harrison
INFO:root:Retweeted tweet from ·µó·µí·µà·µàÀ°·µâ ≥·µé ùêáùêàùêåùêÄùêñùêÄùêëùêà
INFO:root:Retweeted tweet from Joshua Verwers
INFO:root:Retweeted tweet from Mojibola
INFO:root:Retweeted tweet from Farzal Khan
INFO:root:API created
INFO:root:Searching for tweets
INFO:root:API created
INFO:root:Searching for tweets
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from The vrge
INFO:root:Retweeted tweet from Black Fox
INFO:root:Retweeted tweet from KWKI223
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Tim (from First Time Watchers)
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from AJ Morris @ home!
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Mojibola
INFO:root:Retweeted tweet from Aaron Waller
INFO:root:Retweeted tweet from We For News
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from @FitCasually ‚Ñ¢ üì∑
INFO:root:Retweeted tweet from Vanprob Solutions
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from FamousPixs
INFO:root:Retweeted tweet from Gloria Barbie
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Mojibola
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from aly üå± BNHA 288
INFO:root:Retweeted tweet from Sarudzayi Marufu
INFO:root:Retweeted tweet from Gabriele Ginghini
INFO:root:Retweeted tweet from CANON India
INFO:root:Retweeted tweet from Carlos Qui√±onez
INFO:root:Retweeted tweet from naomi‚Å∑ üíå
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Simeilia H-Dallaway
INFO:root:Retweeted tweet from cAm üá¶üá∑üåàüåø
INFO:root:Retweeted tweet from A Follower
INFO:root:Retweeted tweet from David P√©rez üá™üá¶
INFO:root:Retweeted tweet from Matt Smart
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from LUMIX S1 „Éï„Ç°„É≥
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    api.retweet(tweet.id)
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from PhotoPlus Magazine
INFO:root:Retweeted tweet from Scott Waldron
INFO:root:Retweeted tweet from Vuong Pham a bit salty. Doing the needful
INFO:root:Retweeted tweet from Eugenia Loli
INFO:root:Retweeted tweet from Tommi Forsstr√∂m (H-1B immigrant)
INFO:root:Retweeted tweet from Steve Brazill
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from londonphoto
INFO:root:Retweeted tweet from OpenZone
INFO:root:Retweeted tweet from Joseph Cristina
INFO:root:Retweeted tweet from Camera Times
INFO:root:Retweeted tweet from Todofuji
INFO:root:Retweeted tweet from @FitCasually ‚Ñ¢ üì∑
INFO:root:Retweeted tweet from donafilm
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from techandphoto
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from FujixPhotographyUK
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Total BioPharma
INFO:root:Retweeted tweet from Nikon D3200
INFO:root:Retweeted tweet from Fujifilm India
INFO:root:Retweeted tweet from Riccardo Mori
INFO:root:Retweeted tweet from Fujifilm Cellular Dynamics
INFO:root:Retweeted tweet from WebWire
INFO:root:Retweeted tweet from Screen Print India
INFO:root:Retweeted tweet from FujifilmX India
INFO:root:Retweeted tweet from Nikon India Official
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Nikon India Official
INFO:root:Retweeted tweet from yik keng chan bird
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Web & Cloud LLC
INFO:root:Retweeted tweet from londonphoto
INFO:root:Retweeted tweet from Rick Friedman Photography
INFO:root:Retweeted tweet from Rick Friedman
INFO:root:Retweeted tweet from IlorinWeddingPhotoGrapher
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from viktor w√•gman
INFO:root:Retweeted tweet from londonphoto
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Juan Matias
INFO:root:Retweeted tweet from Park Cameras
INFO:root:Retweeted tweet from michaelmagcamit
INFO:root:Retweeted tweet from Mary
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from FamousPixs
INFO:root:Retweeted tweet from FamousPixs
INFO:root:Retweeted tweet from StudioShooter
INFO:root:Retweeted tweet from Finding Range
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Mpumelelo Macu
INFO:root:Retweeted tweet from Y.M.Cinema Magazine
INFO:root:Retweeted tweet from David O'Callaghan
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Wilkinson Cameras
INFO:root:Retweeted tweet from Â§ßÊä§Ê≥ï
INFO:root:Retweeted tweet from Salisbury Indies
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Daniel Devine
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from KameraCrafts
INFO:root:Retweeted tweet from Daniel Belo
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from @FitCasually ‚Ñ¢ üì∑
INFO:root:Retweeted tweet from @FitCasually ‚Ñ¢ üì∑
INFO:root:Retweeted tweet from londonphoto
INFO:root:Retweeted tweet from Cool Article Spinner
INFO:root:Retweeted tweet from LGTWO‚Ñ† (Drop Your Link In Our Pin Tweet)
INFO:root:Retweeted tweet from üéÄT-Roxyü¶ñ
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Paul Simpson (SFB)
INFO:root:Retweeted tweet from ‡º∫ ùêéùêûùê≠ùê¢ùê±00 ‡ºª
INFO:root:Retweeted tweet from Kenn
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from @network_easy
INFO:root:Retweeted tweet from House Redeye
INFO:root:Retweeted tweet from @Dailyusanews
INFO:root:Retweeted tweet from Loud Mouth Pro Gaming
INFO:root:Retweeted tweet from Giuseppe Nelva
INFO:root:Retweeted tweet from Spatial Network
INFO:root:Retweeted tweet from FueledByTy
INFO:root:Retweeted tweet from ÊæÑ„Åø„Çè„Åü„ÇãÊ£Æ
INFO:root:Retweeted tweet from common_guy96
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Ryan GoFett24
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Begaria
INFO:root:Retweeted tweet from Begaria
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from Rooster Cogburn
ERROR:root:Error on retweet
Traceback (most recent call last):
  File "/Users/mikeysan/development/GitHub/retweet_anything/phoducation-bot/searches.py", line 45, in search_tweets
    logger.info(f"Retweeted tweet from {tweet.user.name}")
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 252, in _call
    return method.execute()
  File "/Users/mikeysan/.pyenv/versions/3.8.5/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 327, 'message': 'You have already retweeted this Tweet.'}]
INFO:root:Retweeted tweet from khatong
INFO:root:Retweeted tweet from MeThe31st
INFO:root:Retweeted tweet from donovan
INFO:root:Retweeted tweet from Davon Sexton
INFO:root:API created
INFO:root:Searching for tweets
INFO:root:Retweeted tweet from pink ghost
INFO:root:Retweeted tweet from Lucian Andrei
INFO:root:Retweeted tweet from jenderton4
